# This file is a template, and might need editing before it works on your project.
# You can copy and paste this template into a new `.gitlab-ci.yml` file.
# You should not add this template to an existing `.gitlab-ci.yml` file by using the `include:` keyword.
#
# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Go.gitlab-ci.yml
image: golang:latest

stages:
  - build
  - test
  #- build-docker-image
  #- deploy

compile:
  stage: build
  tags:
    - docker
  script:
    - mkdir -p binaries
    - go build -o binaries ./...
  artifacts:
    paths:
      - binaries

test:
  stage: test
  tags:
    - docker
  script:
    - go test ./... -v

#build-docker-image:
#  stage: build-docker-image
#  image: docker:latest
#  tags: 
#    - docker-build
#  only:
#    - main
#  services:
#    - docker:dind
#  variables:  # not strictly needed, depending on runner configuration
#    DOCKER_HOST: "tcp://docker:2375"
#    DOCKER_TLS_CERTDIR: ""

#    IMAGE_NAME: "monitoring-service:x86"
#    AZURE_REGISTRY_USERNAME: $CI_REGISTRY_USER
#    AZURE_REGISTRY_PASSWORD: $CI_REGISTRY_PASSWORD
#    AZURE_REGISTRY: dentanoidregistry.azurecr.io

#  script:
#    - touch .env
#    - echo -e "MONGO_URI = $MONGO_URI \n" >> .env
#    - echo "BROKER_URL = $BROKER_URL" >> .env
#    - docker context ls
#    - docker info
#    - docker buildx create --use
#    - docker buildx build --platform linux/amd64 -t $IMAGE_NAME . --load
#    - docker tag $IMAGE_NAME $AZURE_REGISTRY/services/monitoring
#    - docker login $AZURE_REGISTRY -u $AZURE_REGISTRY_USERNAME -p $AZURE_REGISTRY_PASSWORD
#    - docker push $AZURE_REGISTRY/services/monitoring
#    - docker images

#deploy:
#  stage: deploy
#  tags:
#    - docker
#  only:
#    - main
#  image:
#    name: mcr.microsoft.com/azure-cli
#    entrypoint: [""]
#  script:
#    - az login --service-principal -u "$AZURE_CLIENT_ID" -p "$AZURE_CLIENT_SECRET" --tenant "$AZURE_TENANT_ID"
#    - az container delete --name monitoring-service --resource-group Dentanoid --yes
#    - az container create --resource-group Dentanoid --name monitoring-service --image dentanoidRegistry.azurecr.io/services/monitoring:latest --registry-username "$CI_REGISTRY_USER" --registry-password  #"$CI_REGISTRY_PASSWORD" --restart-policy Always
